Show upcoming events on home page
jordanopensource/portal-web pull request #178
Opened 2022-03-05 02:32 UTC by alsahawneh

2022-03-07 12:58 UTC, thread-koder commented
Hello @alsahawneh, hope you are having a nice day, there is something wrong with the CSS of the upcoming events section as you can see in the image that I attached
![image](https://user-images.githubusercontent.com/48834143/157038731-eb54139c-52a1-4083-8f2c-d3876235cef0.png)

2022-03-07 13:05 UTC, thread-koder commented on pages/index.vue
> +      <eventList
@alsahawneh in the eventList component you marked the category prop as required in the component yet you didn't pass it here, if you allow me I have some suggestions, you could change the category prop from required to giving it a default value and required to false or pass the category to the component so we can get rid of the error.
Thank you.

2022-03-14 12:12 UTC, alsahawneh commented on pages/index.vue
> +      <eventList
Thanks, you were right. I have just noticed that the event section is not vertically aligned with the heading above. I am currently working on that. Will push the changes ASAP.

2022-03-14 12:14 UTC, alsahawneh commented on pages/index.vue
> +      <eventList
Apart from that, @mahasneh do you think it's better to create a new component for EventsSpotlight or to keep the code as it is?

2022-03-28 18:22 UTC, mahasneh requested changes

2022-03-30 13:51 UTC, mahasneh requested changes
Change the code as commented.

2022-03-30 14:00 UTC, alsahawneh commented on components/Events/EventsSpotlight.vue
> +  <section>
Done.

2022-03-30 14:01 UTC, merged