Style blockquotes
jordanopensource/portal-web pull request #190
Opened 2022-03-28 18:15 UTC by alsahawneh

Closes #124

2022-03-29 12:48 UTC, mahasneh requested changes

2022-03-29 12:48 UTC, mahasneh commented on components/Blog/BlogSingle.vue
> +  border-left: 1rem solid #eeeeee;
Please consider using Tailwind directives, like `@apply`

2022-03-29 12:48 UTC, mahasneh commented on components/Blog/BlogSingle.vue
> +  border-left: 1rem solid #eeeeee;
Use pre-configured colors rather than hexadecimals, like `josa-warm-grey-light`, check [here](https://github.com/jordanopensource/portal-web/blob/main/tailwind.config.js).

2022-03-29 14:48 UTC, alsahawneh commented on components/Blog/BlogSingle.vue
> +  border-left: 1rem solid #eeeeee;
Done

2022-03-29 14:49 UTC, alsahawneh commented on components/Blog/BlogSingle.vue
> +  border-left: 1rem solid #eeeeee;
Done. But I kept the border as it was since Tailwind does not include borders wider than 8px.

2022-03-30 12:37 UTC, mahasneh approved these changes
Looks good

2022-03-30 12:37 UTC, merged