Add a "Read translation link" at the end of an article if it has a translation
jordanopensource/portal-web pull request #311
Opened 2021-04-29 12:04 UTC by fmubaidien

Resolves #280

2021-04-29 12:05 UTC, fmubaidien commented
When reviewing please make sure my CSS is correct and that I created the link in the best way possible

2021-04-29 12:22 UTC, wissamataleh commented on components/Blog/BlogSingle.vue
> +        <nuxt-link v-if="article.translations.length && article.language==='en'"
- I suggest iterating and listing all available translations, and displaying the link text depending on the translation language. This allows for scaling up without the need for updating the code whenever a new locale is added, also less code.
- The link has to point to the localized path.
- Use translatable strings instead of hard coding the text.
- The location of this should be on the top of the article under the publication date.

2021-04-29 12:24 UTC, wissamataleh requested changes
- I suggest iterating and listing all available translations, and displaying the link text depending on the translation language. This allows for scaling up without the need for updating the code whenever a new locale is added, also less code.
- The link has to point to the localized path.
- Use translatable strings instead of hard coding the text.
- The location of this should be on the top of the article under the publication date.

2021-04-30 21:39 UTC, wissamataleh commented
071bde9 Because the `locale` argument in `$t` is buggy and not working as expected.

2021-04-30 22:49 UTC, wissamataleh commented
071bde9 Because the `locale` argument in `$t` is buggy and not working as expected.
01d7fe5 To fix data fetching issue.

2021-05-03 10:05 UTC, wissamataleh approved these changes

2021-05-03 10:05 UTC, merged