Add to calendar
jordanopensource/portal-web pull request #348
Opened 2021-06-05 12:39 UTC by Ashaqra

2021-06-06 13:50 UTC, mahasneh commented on components/Events/AddToCalender.vue
> +          desc.substring(0, 200) + "..." +
Make newlines to `\n` and no need to be limited to 200.

2021-06-06 13:55 UTC, mahasneh commented on lang/en.js
> +  addToCalender:{
Fix typo

2021-06-06 13:57 UTC, mahasneh commented on lang/en.js
> +    Google:'Google',
Camel case, please. 🐪

2021-06-16 14:29 UTC, wissamataleh requested changes

2021-06-17 11:29 UTC, wissamataleh commented on components/Events/AddToCalender.vue
> +  :dir(rtl).icon {
You just did the same thing in a different way. What you need is to have `ml-2 mr-0` for `LTR` and `mr-2 ml-0` for `RTL`

2021-06-17 11:31 UTC, wissamataleh commented on components/Events/AddToCalender.vue
> +        if(this.Opened == true){
This can be done with one line `this.Opended = !this.Opened` 
also use camelCase to name your variables.

2021-06-17 11:35 UTC, wissamataleh commented on lang/en.js
> +  addToCalender:{
@Ashaqra Also fix typo in component name

2021-06-17 14:04 UTC, closed without merging

2021-06-17 14:08 UTC, wissamataleh commented
This is a mess, Im closing this PR. Please fix your branch and commits, and open a new PR, with clean code, clean commits.