Fix meta description given null value
jordanopensource/portal-web pull request #351
Opened 2021-06-15 16:46 UTC by Ashaqra

2021-06-15 16:48 UTC, geokhoury commented
#### 📝Changed routes:


| [**/info/_slug**](https://portal-web-1jsjkdanm-josa.vercel.app/info/_slug) | [**/programs/_id/_slug**](https://portal-web-1jsjkdanm-josa.vercel.app/programs/_id/_slug) |
|:-:|:-:|
|<a href="https://portal-web-1jsjkdanm-josa.vercel.app/info/_slug"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/1Rs9R7hQ8vh9Ee-2VDmpHaQEpiEQ_OBY4PBCyjRDsdIKYM6WERQBipby2Bg6mwNY5q6oj675Zie8tgZj6YarDw.png&w=600" alt="Screenshot of /info/_slug" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/lBgSbC9HJ2yCYTwWfwI9XMHEo6tmneoD6f_1t9CdQm_17p5NI8pkdKYEydSurv1ubxiDdpN6THuns1jX7UpuCQ.png">(view full size)</a> |<a href="https://portal-web-1jsjkdanm-josa.vercel.app/programs/_id/_slug"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/LlOmmQPZ0S4tzxCGFY5o0vkQ3aHD4V79abKVr3j0RvOF8H5HDELdKx2NcGigy06RFHKH4MVLjQuhB2XpkvUS7w.png&w=600" alt="Screenshot of /programs/_id/_slug" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/7XlfNTCpCPx6_WRY5UUxIG7BH-Mq0ORRUmr6tRZtLlxKVV7SriaFS6CTMZ1Flt4y4hhAwa0pWvZEem2rm7xALg.png">(view full size)</a> |



| [**/programs**](https://portal-web-1jsjkdanm-josa.vercel.app/programs) |
|:-:|
|<a href="https://portal-web-1jsjkdanm-josa.vercel.app/programs"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/oqwQSqICtjwFnQ0pp27UvPpJlJihQY7r6wWmILHNIZcD2SZm6_FcJpDpk9cChIfPE_kzskKOPxv0yeR4gUW7RA.png&w=600" alt="Screenshot of /programs" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/gYc5ThWEw3UzwfjiZAUOkUFm6ZY-V0awHLWcB4cyLdThuruvdFFTgDXKpbjwdD9LwVdvipGdN7puKkSy1G9h1w.png">(view full size)</a> |







Commit 906dfec62106549975200ce9d13d6c38ef9b8cca (https://portal-web-1jsjkdanm-josa.vercel.app).

2021-06-16 09:24 UTC, wissamataleh requested changes

2021-06-16 09:24 UTC, wissamataleh commented on pages/info/_slug.vue
> +      console.log(this.pageContent)
Remove line

2021-06-16 09:24 UTC, wissamataleh commented on pages/programs/_id/_slug.vue
> +            content: this.program['description_' + this.$i18n.locale] ? this.program[
"metaDescription" field should be used for the meta content, if empty "description" can be used as fallback

2021-07-10 09:10 UTC, merged